const T = "https://minecraft.wiki/w/Special:FilePath/";
const IMAGE_URLS = {
  // Hostile Mobs
  "Creeper":           T+"Creeper.png",
  "Zombie":            T+"Zombie.png",
  "Skeleton":          T+"Skeleton.png",
  "Spider":            T+"Spider.png",
  "Enderman":          T+"Enderman.png",
  "Witch":             T+"Witch.png",
  "Blaze":             T+"Blaze.png",
  "Ghast":             T+"Ghast.png",
  "Slime":             T+"Slime.png",
  "Cave Spider":       T+"Cave_Spider.png",
  "Wither Skeleton":   T+"Wither_Skeleton.png",
  "Pillager":          T+"Pillager.png",
  "Phantom":           T+"Phantom.png",
  "Guardian":          T+"Guardian.png",
  "Warden":            T+"Warden.png",
  "Husk":              T+"Husk.png",
  "Drowned":           T+"Drowned.png",
  "Magma Cube":        T+"Magma_Cube.png",
  "Endermite":         T+"Endermite.png",
  "Silverfish":        T+"Silverfish.png",
  // Passive Mobs
  "Steve":             T+"Steve.png",
  "Alex":              T+"Alex.png",
  "Cow":               T+"Cow.png",
  "Pig":               T+"Pig.png",
  "Chicken":           T+"Chicken.png",
  "Sheep":             T+"Sheep.png",
  "Horse":             T+"Horse.png",
  "Villager":          T+"Villager.png",
  "Wolf":              T+"Wolf.png",
  "Cat":               T+"Cat.png",
  "Rabbit":            T+"Rabbit.png",
  "Bee":               T+"Bee.png",
  "Fox":               T+"Fox.png",
  "Axolotl":           T+"Axolotl.png",
  "Iron Golem":        T+"Iron_Golem.png",
  "Snow Golem":        T+"Snow_Golem.png",
  "Mooshroom":         T+"Mooshroom.png",
  "Panda":             T+"Panda.png",
  "Turtle":            T+"Turtle.png",
  "Dolphin":           T+"Dolphin.png",
  "Parrot":            T+"Parrot.png",
  "Llama":             T+"Llama.png",
  "Squid":             T+"Squid.png",
  "Bat":               T+"Bat.png",
  // Blocks
  "Grass Block":       T+"Grass_Block.png",
  "TNT":               T+"TNT.png",
  "Chest":             T+"Chest.png",
  "Crafting Table":    T+"Crafting_Table.png",
  "Furnace":           T+"Furnace.png",
  "Bookshelf":         T+"Bookshelf.png",
  "Pumpkin":           T+"Pumpkin.png",
  "Jack o'Lantern":    T+"Jack_o'Lantern.png",
  "Cake":              T+"Cake.png",
  "Beacon":            T+"Beacon.png",
  "Enchanting Table":  T+"Enchanting_Table.png",
  "Diamond Ore":       T+"Diamond_Ore.png",
  "Emerald Ore":       T+"Emerald_Ore.png",
  "Gold Ore":          T+"Gold_Ore.png",
  "Obsidian":          T+"Obsidian.png",
  "End Portal Frame":  T+"End_Portal_Frame.png",
  "Nether Portal":     T+"Nether_Portal.png",
  "Dragon Egg":        T+"Dragon_Egg.png",
};
