// Animal cartoon images — Twemoji SVG emoji for most animals
// (12 without a dedicated emoji keep their Wikipedia photo and get AI background removal)
const T = "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/";

const IMAGE_URLS = {
  // ── Mammals ───────────────────────────────────────────────────────────────
  "Lion":          T + "1f981.svg",
  "Tiger":         T + "1f42f.svg",
  "Elephant":      T + "1f418.svg",
  "Giraffe":       T + "1f992.svg",
  "Zebra":         T + "1f993.svg",
  "Leopard":       T + "1f406.svg",
  "Cheetah":       "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Male_cheetah_facing_left_in_South_Africa.jpg/330px-Male_cheetah_facing_left_in_South_Africa.jpg",
  "Bear":          T + "1f43b.svg",
  "Wolf":          T + "1f43a.svg",
  "Fox":           T + "1f98a.svg",
  "Rabbit":        T + "1f430.svg",
  "Kangaroo":      T + "1f998.svg",
  "Giant Panda":   T + "1f43c.svg",
  "Gorilla":       T + "1f98d.svg",
  "Chimpanzee":    T + "1f412.svg",
  "Hippopotamus":  T + "1f99b.svg",
  "Rhinoceros":    T + "1f98f.svg",
  "Camel":         T + "1f42a.svg",
  "Deer":          T + "1f98c.svg",
  "Polar Bear":    T + "1f43b-200d-2744-fe0f.svg",
  // ── Birds ─────────────────────────────────────────────────────────────────
  "Eagle":         T + "1f985.svg",
  "Penguin":       T + "1f427.svg",
  "Parrot":        T + "1f99c.svg",
  "Flamingo":      T + "1f9a9.svg",
  "Peacock":       T + "1f99a.svg",
  "Owl":           T + "1f989.svg",
  "Toucan":        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Toucans_%28Ramphastidae%29.jpg/330px-Toucans_%28Ramphastidae%29.jpg",
  "Swan":          T + "1f9a2.svg",
  "Hummingbird":   "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Trinidad_and_Tobago_hummingbirds_composite.jpg/330px-Trinidad_and_Tobago_hummingbirds_composite.jpg",
  "Ostrich":       "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Struthio_Diversity.jpg/330px-Struthio_Diversity.jpg",
  // ── Reptiles ──────────────────────────────────────────────────────────────
  "Crocodile":     T + "1f40a.svg",
  "Snake":         T + "1f40d.svg",
  "Turtle":        T + "1f422.svg",
  "Chameleon":     "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Chamaeleonidae-01.jpg/330px-Chamaeleonidae-01.jpg",
  "Iguana":        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Green_Iguana_In_Florida.jpg/330px-Green_Iguana_In_Florida.jpg",
  "Komodo Dragon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/202306_Varanus_komodoensis.jpg/330px-202306_Varanus_komodoensis.jpg",
  // ── Sea ───────────────────────────────────────────────────────────────────
  "Dolphin":       T + "1f42c.svg",
  "Shark":         T + "1f988.svg",
  "Blue Whale":    T + "1f40b.svg",
  "Octopus":       T + "1f419.svg",
  "Jellyfish":     "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jelly_cc11.jpg/330px-Jelly_cc11.jpg",
  "Seahorse":      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg/330px-Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg",
  "Crab":          T + "1f980.svg",
  "Clownfish":     T + "1f420.svg",
  "Starfish":      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Starfish_montage.png/330px-Starfish_montage.png",
  // ── Insects ───────────────────────────────────────────────────────────────
  "Butterfly":     T + "1f98b.svg",
  "Bee":           T + "1f41d.svg",
  "Dragonfly":     "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Gemeine_Heidelibelle_%28Sympetrum_vulgatum%29_4.jpg/330px-Gemeine_Heidelibelle_%28Sympetrum_vulgatum%29_4.jpg",
  "Ladybug":       T + "1f41e.svg",
  "Ant":           T + "1f41c.svg",
  // ── Farm ──────────────────────────────────────────────────────────────────
  "Cow":           T + "1f404.svg",
  "Horse":         T + "1f40e.svg",
  "Pig":           T + "1f437.svg",
  "Chicken":       T + "1f414.svg",
  "Sheep":         T + "1f411.svg",
  "Goat":          T + "1f410.svg",
  "Duck":          T + "1f986.svg",
  "Donkey":        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Donkey_in_Clovelly%2C_North_Devon%2C_England.jpg/330px-Donkey_in_Clovelly%2C_North_Devon%2C_England.jpg",
};
